name: Muthukumaran-Test
on:
   push:
     branches: [main]
   pull_request:
     branches: [main]
   workflow_dispatch:
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug
            
      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress
      
          
      - name: Run tests with phpunit/phpunit
        run: vendor/bin/phpunit --coverage-clover code-coverage.xml --log-junit test-report.xml
          
      - name: Fix code coverage paths
        run: sed -i 's@'$GITHUB_WORKSPACE'/@/@g' code-coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: 60fced35a652dffaca2d8a2059fc445f5e10afc7
