name: Muthukumaran-Test
on:
   push:
     branches: [main]
   workflow_dispatch:
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Download code-coverage.xml
        uses: actions/download-artifact@v3
        with:
          name: coverage-xml-artifact
          path: /composer.json
