name: Print Message

on:
  push:
    branches:
      - main

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
    - name: Print Message
      run: echo "Hello, world! ${{ vars.TEST_VARIABLE }}"
